### ISSUE TITLE
Export stops short when tracklog folder is missing.

### ISSUE THREAD

**Issue by philderbeast** [kuaka/fsdb_igc#3]
For the HG worlds in Italy, no tracks are available for the training day from [Airtribune](https://airtribune.com/22nd-fai-world-hg-championship/results) at least.

```
> nix-shell -p 'python3.withPackages(ps: with ps; [ lxml ])'
[nix-shell:~/dev/src/.../2019-italy-score]$ python fsdb_igc.py italy2019.fsdb
...
Training Day
2019-07-14 does not exist
```

```
> tree -d
.
├── 2019-07-15
├── 2019-07-16
├── 2019-07-17
├── 2019-07-19
├── 2019-07-20
├── 2019-07-22
├── 2019-07-23
├── 2019-07-24
├── 2019-07-26
└── output
    └── 2019-07-14
```

Please allow zipping of the remaining tasks, adding a `--keep-going` flag if necessary.

If I create the missing folder, the script stops short because it can't find a pilot's track.

```
> mkdir 2019-07-14
> nix-shell -p 'python3.withPackages(ps: with ps; [ lxml ])'
[nix-shell:~/dev/src/.../2019-italy-score]$ python fsdb_igc.py italy2019.fsdb
...
Training Day
pil_id='6' name='Craig_Taylor' tracklog='LiveTrack Craig Taylor.656864.20190714-114929.6075.6.igc'
Traceback (most recent call last):
  File "fsdb_igc.py", line 79, in <module>
    main(args)
  File "fsdb_igc.py", line 61, in main
    shutil.copy2(os.path.join(source, tracklog), out)
  File "/nix/store/px24kgsz8wpnfs0zv5zg28l66myzw3ki-python3-3.8.6/lib/python3.8/shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/nix/store/px24kgsz8wpnfs0zv5zg28l66myzw3ki-python3-3.8.6/lib/python3.8/shutil.py", line 261,
in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory:
'2019-07-14/LiveTrack Craig Taylor.656864.20190714-114929.6075.6.igc'
```

**Comment by kuaka** [comment]
I have pushed https://github.com/kuaka/fsdb_igc/commit/7c6f649977b2b3a8cb4009f9ef0693ea38b97888 to address this.
Tested by removing source folders before running script.
copes with missing igc files also (always did but there was no feedback)

**Comment by kuaka** [comment]
@philderbeast if this adequately resolves your issue please close.

**Comment by philderbeast** [comment]
I got zips, thank you.

```
[nix-shell:~/dev/src/.../2019-italy-score]$ python fsdb_igc.py italy2019.fsdb
...
Training Day
pil_id=6 name=Craig_Taylor_6 tracklog=LiveTrack Craig Taylor.656864.20190714-114929.6075.6.igc
LiveTrack Craig Taylor.656864.20190714-114929.6075.6.igc does not exist. Skipping
...
LiveTrack Piers Throssell.288351.20190714-110128.60026.98.igc does not exist. Skipping
Task 1
pil_id=5 name=Peter_Burkitt_5 tracklog=LiveTrack Peter Burkitt.790115.20190715-111942.7381.5.igc
...
pil_id=60 name=Georg_Schweier_60 tracklog=Georg.60.igc
Task 6
__TASK6 does not exist. Skipping
Task 7
Kajo_Clauss_55 does not have a tracklog in fsdb file.
pil_id=6 name=Craig_Taylor_6 tracklog=LiveTrack Craig Taylor.656864.20190722-113938.6075.6.igc
...
```
